export const NOTIFY_USER = 'NOTIFY_USER';
export const DISEABLE_BALANCE_ON_ADD = 'DISEABLE_BALANCE_ON_ADD';
export const DISEABLE_BALANCE_ON_EDIT = 'DISEABLE_BALANCE_ON_EDIT';
export const ALLOW_REGISTRATION = 'ALLOW_REGISTRATION';
